# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do
  lane :custom_lane do|options|
    branch = options[:branch]
    build_no = get_version_number + '.' + Time.new.strftime("%m%d%H%M")
    puts "Begin to run ci"
    sh "pwd" # => "[root]/fastlane"
    puts Dir.pwd # => "[root]/fastlane"
   #确认分支、git状态、拉取最新代码
    sh "git checkout #{branch}"
    ensure_git_branch(branch: branch)
    ensure_git_status_clean
    git_pull

   #递增build number
    increment_build_number(build_number: build_no)
#开始打包
  gym(
      export_method:"development",
      output_directory:"./fastlane/build",
    ) 
#使用fir-cli上传ipa
    sh "fir publish ./fastlane/build/Product.ipa -T 3b0eb703462f81f0348ac58c91b171d7"
  end	
end
